[package]
name = "chunkdrive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.69"
rand = "0.8.5"
serde = "1.0.164"
serde_yaml = "0.9.22"
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio = { version = "1", features = ["full"] }
typetag = "0.2.8"
rust-crypto = "0.2.36"
async-recursion = "1.0.4"
