name: Build artifacts

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux-amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          
          - name: linux-i686
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
            cross: false
            
            
          - name: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true

          - name: linux-armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cross: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install rustup target
        run: rustup target add ${{ matrix.target }}
      - name: Install cross
        if: matrix.cross
        run: cargo install cross
      - name: Build
        if: "!matrix.cross"
        run: cargo build --target ${{ matrix.target }} --release
      - name: Build
        if: matrix.cross
        run: cross build --target ${{ matrix.target }} --release
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/chunkdrive
          retention-days: 3